C4CGreenmeBundle:
  resource: C4C\Bundle\GreenmeBundle\Controller\DefaultController
  type: annotation

C4CGreenmeBundle_ReportAPI:
  resource: C4C\Bundle\GreenmeBundle\Controller\ReportAPIController
  type: rest

C4CGreenmeBundle_FootprintAPI:
  resource: C4C\Bundle\GreenmeBundle\Controller\FootprintAPIController
  type: rest