# C4CGreenmeBundle:
#   resource: "@C4CGreenmeBundle/Controller/"
#   type: annotation
#   prefix: /api

C4CGreenmeBundle_ReportAPI:
  resource: C4C\Bundle\GreenmeBundle\Controller\ReportAPIController
  type: rest

C4CGreenmeBundle_FootprintAPI:
  resource: C4C\Bundle\GreenmeBundle\Controller\FootprintAPIController
  type: rest